// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEc6gMP_Bl0upOFyNd7dZP8xs-S0CVaHw',
    appId: '1:560425340935:web:acfac66f3a64483ed99aa2',
    messagingSenderId: '560425340935',
    projectId: 'smash-match-ultimate',
    authDomain: 'smash-match-ultimate.firebaseapp.com',
    storageBucket: 'smash-match-ultimate.firebasestorage.app',
    measurementId: 'G-Y00VHBENX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMD7yMnZlmPdRH4k8JEGgoYEegsNwNgys',
    appId: '1:560425340935:android:3622fb79444055c8d99aa2',
    messagingSenderId: '560425340935',
    projectId: 'smash-match-ultimate',
    storageBucket: 'smash-match-ultimate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh32RbHXsxp-zd0SoYAzJ2GJ9zd8C4DWI',
    appId: '1:560425340935:ios:058fbbe925d22844d99aa2',
    messagingSenderId: '560425340935',
    projectId: 'smash-match-ultimate',
    storageBucket: 'smash-match-ultimate.firebasestorage.app',
    iosBundleId: 'com.example.memoryGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh32RbHXsxp-zd0SoYAzJ2GJ9zd8C4DWI',
    appId: '1:560425340935:ios:058fbbe925d22844d99aa2',
    messagingSenderId: '560425340935',
    projectId: 'smash-match-ultimate',
    storageBucket: 'smash-match-ultimate.firebasestorage.app',
    iosBundleId: 'com.example.memoryGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEc6gMP_Bl0upOFyNd7dZP8xs-S0CVaHw',
    appId: '1:560425340935:web:90a6a18eca7f5bf8d99aa2',
    messagingSenderId: '560425340935',
    projectId: 'smash-match-ultimate',
    authDomain: 'smash-match-ultimate.firebaseapp.com',
    storageBucket: 'smash-match-ultimate.firebasestorage.app',
    measurementId: 'G-915RT7BSWT',
  );

}